


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."tb_addresses" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid",
    "contact_name" "text",
    "contact_phone" "text",
    "province_id" smallint,
    "ward_id" smallint,
    "address_detail" "text",
    "is_default" boolean DEFAULT false
);


ALTER TABLE "public"."tb_addresses" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tb_notifications" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid",
    "title" "text",
    "content" "text",
    "order_id" "uuid",
    "is_read" boolean DEFAULT false
);


ALTER TABLE "public"."tb_notifications" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tb_order_tracking" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "order_id" "uuid",
    "status" "text",
    "note" "text",
    "updated_by" "uuid"
);


ALTER TABLE "public"."tb_order_tracking" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tb_orders" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid",
    "pickup_address_id" "uuid",
    "receiver_name" "text",
    "receiver_phone" "text",
    "receiver_province_id" smallint,
    "receiver_ward_id" smallint,
    "receiver_address_detail" "text",
    "weight_gram" smallint DEFAULT '100'::smallint,
    "cod_amount" bigint DEFAULT '0'::bigint,
    "shipping_fee" bigint DEFAULT '0'::bigint,
    "delivery_status" "text" DEFAULT 'PENDING'::"text",
    "financial_status" "text" DEFAULT 'unpaid'::"text",
    "parcel_image_url" "text",
    "delivery_proof_url" "text",
    "is_receiver_pay" boolean DEFAULT false,
    "order_contents" "text",
    "shipper_id" "uuid"
);


ALTER TABLE "public"."tb_orders" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tb_provinces" (
    "id" smallint NOT NULL,
    "name" "text" NOT NULL,
    "region" "text"
);


ALTER TABLE "public"."tb_provinces" OWNER TO "postgres";


ALTER TABLE "public"."tb_provinces" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tb_provinces_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tb_users" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email" "text",
    "full_name" "text",
    "role" "text" DEFAULT 'customer'::"text",
    "phone_number" "text"
);


ALTER TABLE "public"."tb_users" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tb_wards" (
    "id" smallint NOT NULL,
    "province_id" smallint NOT NULL,
    "name" "text"
);


ALTER TABLE "public"."tb_wards" OWNER TO "postgres";


ALTER TABLE "public"."tb_wards" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tb_wards_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."tb_addresses"
    ADD CONSTRAINT "tb_addresses_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tb_notifications"
    ADD CONSTRAINT "tb_notifications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tb_order_tracking"
    ADD CONSTRAINT "tb_order_tracking_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tb_orders"
    ADD CONSTRAINT "tb_orders_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tb_provinces"
    ADD CONSTRAINT "tb_provinces_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tb_users"
    ADD CONSTRAINT "tb_users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tb_wards"
    ADD CONSTRAINT "tb_wards_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tb_addresses"
    ADD CONSTRAINT "tb_addresses_province_id_fkey" FOREIGN KEY ("province_id") REFERENCES "public"."tb_provinces"("id");



ALTER TABLE ONLY "public"."tb_addresses"
    ADD CONSTRAINT "tb_addresses_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."tb_users"("id");



ALTER TABLE ONLY "public"."tb_addresses"
    ADD CONSTRAINT "tb_addresses_ward_id_fkey" FOREIGN KEY ("ward_id") REFERENCES "public"."tb_wards"("id");



ALTER TABLE ONLY "public"."tb_notifications"
    ADD CONSTRAINT "tb_notifications_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."tb_orders"("id");



ALTER TABLE ONLY "public"."tb_notifications"
    ADD CONSTRAINT "tb_notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."tb_users"("id");



ALTER TABLE ONLY "public"."tb_order_tracking"
    ADD CONSTRAINT "tb_order_tracking_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."tb_orders"("id");



ALTER TABLE ONLY "public"."tb_order_tracking"
    ADD CONSTRAINT "tb_order_tracking_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "public"."tb_users"("id");



ALTER TABLE ONLY "public"."tb_orders"
    ADD CONSTRAINT "tb_orders_pickup_address_id_fkey" FOREIGN KEY ("pickup_address_id") REFERENCES "public"."tb_addresses"("id");



ALTER TABLE ONLY "public"."tb_orders"
    ADD CONSTRAINT "tb_orders_receiver_province_id_fkey" FOREIGN KEY ("receiver_province_id") REFERENCES "public"."tb_provinces"("id");



ALTER TABLE ONLY "public"."tb_orders"
    ADD CONSTRAINT "tb_orders_receiver_ward_id_fkey" FOREIGN KEY ("receiver_ward_id") REFERENCES "public"."tb_wards"("id");



ALTER TABLE ONLY "public"."tb_orders"
    ADD CONSTRAINT "tb_orders_shipper_id_fkey" FOREIGN KEY ("shipper_id") REFERENCES "public"."tb_users"("id");



ALTER TABLE ONLY "public"."tb_orders"
    ADD CONSTRAINT "tb_orders_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."tb_users"("id");



ALTER TABLE ONLY "public"."tb_wards"
    ADD CONSTRAINT "tb_wards_province_id_fkey" FOREIGN KEY ("province_id") REFERENCES "public"."tb_provinces"("id");





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";





































































































































































GRANT ALL ON TABLE "public"."tb_addresses" TO "anon";
GRANT ALL ON TABLE "public"."tb_addresses" TO "authenticated";
GRANT ALL ON TABLE "public"."tb_addresses" TO "service_role";



GRANT ALL ON TABLE "public"."tb_notifications" TO "anon";
GRANT ALL ON TABLE "public"."tb_notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."tb_notifications" TO "service_role";



GRANT ALL ON TABLE "public"."tb_order_tracking" TO "anon";
GRANT ALL ON TABLE "public"."tb_order_tracking" TO "authenticated";
GRANT ALL ON TABLE "public"."tb_order_tracking" TO "service_role";



GRANT ALL ON TABLE "public"."tb_orders" TO "anon";
GRANT ALL ON TABLE "public"."tb_orders" TO "authenticated";
GRANT ALL ON TABLE "public"."tb_orders" TO "service_role";



GRANT ALL ON TABLE "public"."tb_provinces" TO "anon";
GRANT ALL ON TABLE "public"."tb_provinces" TO "authenticated";
GRANT ALL ON TABLE "public"."tb_provinces" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tb_provinces_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tb_provinces_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tb_provinces_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tb_users" TO "anon";
GRANT ALL ON TABLE "public"."tb_users" TO "authenticated";
GRANT ALL ON TABLE "public"."tb_users" TO "service_role";



GRANT ALL ON TABLE "public"."tb_wards" TO "anon";
GRANT ALL ON TABLE "public"."tb_wards" TO "authenticated";
GRANT ALL ON TABLE "public"."tb_wards" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tb_wards_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tb_wards_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tb_wards_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































